---
- name: Use Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: "chocolatey"
    state: present

- name: Ensure absense of some packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ win_choco_uninstall_choco_packages }}"
    state: present
    force: true

- name: Ensure other packages are present
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ win_choco_install_choco_packages }}"
    state: present
...
