Vagrant.configure(2) do |config|
    # disable guest addtions
    config.ssh.forward_agent = true
    config.vm.synced_folder '.', '/vagrant', disable: true

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "bento/ubuntu-20.04-arm64"
        ubuntu.vm.network "private_network", ip: "192.168.207.128"
        ubuntu.vm.network "forwarded_port", guest: 80, host: 8000
        ubuntu.vm.network "forwarded_port", guest: 443, host: 8443
    end
end