---
# vars file for java

# This part maps a distribution to a version of java.
_java_default_version:
  default: 11
  Alpine: 8
  Amazon: 17
  Debian-12: 17
  Gentoo: 8
  RedHat: 8
  Ubuntu: 19
  Ubuntu-18: 17
  Ubuntu-20: 17
  Ubuntu-24: 21
  Suse: 8
java_default_version: "{{ _java_default_version[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | \
  default(_java_default_version[ansible_distribution]) | \
  default(_java_default_version[ansible_os_family]) | \
  default(_java_default_version['default']) }}"
