---

# Mac
- name: Install miniconda on macos
  become: false
  command: /usr/local/bin/brew install miniconda
  when:
    - ansible_os_family == 'Darwin'
  changed_when: false

# Linux
- name: Install miniconda on Linux
  when: ansible_os_family in ['RedHat', 'Debian']
  block:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - wget
          - bzip2
        state: present

    - name: Download installer
      ansible.builtin.get_url:
        url: "{{ miniconda_installer_url }}"
        dest: "/tmp/{{ miniconda_installer_sh }}"
        mode: '0755'

    - name: Run miniconda installer script
      ansible.builtin.command: /tmp/{{ miniconda_installer_sh }} -b -p {{ miniconda_dir }}
      args:
        creates: "{{ miniconda_bindir }}"

    - name: Delete miniconda installer
      ansible.builtin.file:
        path: "/tmp/{{ miniconda_installer_sh }}"
        state: absent

    - name: Initialize conda for all users
      ansible.builtin.shell: "{{ miniconda_bindir }}/conda init"
      args:
        executable: /bin/bash
      changed_when: true

    - name: Source conda.sh in /etc/bash.bashrc
      ansible.builtin.blockinfile:
        path: "/etc/bash.bashrc"
        state: present
        block: |
          # Initialize miniconda
          .  {{ miniconda_dir }}/etc/profile.d/conda.sh
        marker: '# {mark} ANSIBLE MANAGED BLOCK base_conda'
      when: ansible_os_family == 'Debian'

    - name: Source conda.sh in /etc/bash.bashrc
      ansible.builtin.blockinfile:
        path: "/etc/bashrc"
        state: present
        block: |
          # Initialize miniconda
          .  {{ miniconda_dir }}/etc/profile.d/conda.sh
        marker: '# {mark} ANSIBLE MANAGED BLOCK base_conda'
      when: ansible_os_family == 'RedHat'
...
