---
# tasks file for miniconda
- name: Check os family
  ansible.builtin.debug:
    var: ansible_os_family

- name: Set variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Check presence of conda
  when: ansible_os_family != 'Windows'
  ansible.builtin.stat:
    path: "{{ miniconda_bindir }}/conda"
  register: conda_executable

- name: Show conda presence
  ansible.builtin.debug:
    var: conda_executable

- name: Install miniconda
  ansible.builtin.include_tasks: install.yml
  when: ansible_os_family == 'Windows' or not conda_executable.stat.exists

- name: Task is running from within the role
  ansible.builtin.debug:
    msg: "This is a task from miniconda role."
