---
- name: Destroy
  hosts: localhost
  connection: local
  tasks:
    - name: Delete and purge a VM
      theko2fi.multipass.multipass_vm:
        name: web
        state: absent
        purge: true
