---

- name: Chapter 11 playbook
  hosts: web

  tasks:

    - name: Download goss binary
      delegate_to: localhost
      connection: local
      become: false
      get_url:
        url: "https://github.com/goss-org/goss/releases/download/v0.4.6/goss-linux-amd64"
        dest: "~/Downloads/goss"
        mode: '0755'
      register: result
      ignore_errors: true

    - name: Show download result
      debug:
        var: result
