---

- name: Show usage of limit option
  hosts: multipass

  tasks:
    - name: Greeting from targets
      debug:
        msg: "Hello from {{ ansible_facts['hostname'] }}"

- name: Show usage of delegate_to option
  hosts: multipass

  tasks:

    - name: Download goss binary
      delegate_to: localhost
      connection: local
      become: false
      get_url:
        url: "https://github.com/goss-org/goss/releases/download/v0.4.6/goss-linux-amd64"
        dest: "~/Downloads/goss"
        mode: '0755'
      register: result
      ignore_errors: true

    - name: Show download result
      debug:
        var: result
