---

- name: Show usage of limit option
  hosts: node1
  vars:
    fruits:
      - Apple
      - Banana

  tasks:
    - name: Greeting from targets
      debug:
        msg: "Hello from {{ ansible_facts['hostname'] }}"

    - name: Test if fruit is in list
      debug:
        msg: fruit is in list
      when: "'Pear' in ['Pear', 'Apple']"

- name: Show usage of delegate_to option
  hosts: node1

  tasks:

    - name: Download goss binary
      delegate_to: localhost
      connection: local
      become: false
      get_url:
        url: "https://github.com/goss-org/goss/releases/download/v0.4.6/goss-linux-amd64"
        dest: "~/Downloads/goss"
        mode: '0755'
      register: result
      ignore_errors: true

    - name: Show download result
      debug:
        var: result

- name: Manually gathering ansible_facts
  hosts: node1
  gather_facts: false
  become: false
  tasks:
    - name: Gather facts
      setup:

    - name: Retrieve ip address of network interface enp0s1
      debug:
        var: ansible_enp0s1.ipv4.address

- name: Upgrade 50% of web servers
  hosts: multipass
  serial:
    - 1
    - 70%
  tasks:
    - name: Greeting from targets
      ansible.builtin.debug:
        msg: "Hello from {{ ansible_facts['hostname'] }}"

- name: Generate a keyfile
  hosts: multipass
  tasks:
    - name: Check if rskeyfile exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: ./rskeyfile
      register: key_file
      run_once: true

    - name: Generate key file, run only once on localhost
      delegate_to: localhost
      ansible.builtin.shell: openssl rand -base64 756 > rskeyfile
      run_once: true
      when: not key_file.stat.exists
      register: created_output
      changed_when: created_output.rc != 0

    - name: Change keyfile ownership
      delegate_to: localhost
      ansible.builtin.command: chmod 400 ./rskeyfile
      run_once: true
      register: ownership_output
      changed_when: ownership_output.rc != 0
      when: not key_file.stat.exists
