Vagrant.configure(2) do |config|

    # Forward ssh-agent for cloning from Github.com
    config.ssh.forward_agent = true

    config.vm.define "web" do |web|
        web.vm.box = "bento/centos-stream-9"
        web.vm.hostname = "web"
        web.vm.network "forwarded_port", guest: 80, host: 8000
        web.vm.network "forwarded_port", guest: 443, host: 8443
    end
end