Vagrant.configure(2) do |config|

    # Forward ssh-agent for cloning from Github.com
    config.ssh.forward_agent = true

    config.vm.define "web" do |web|
        web.vm.box = "bento/centos-stream-9"
        web.vm.hostname = "web"
    end

    config.vm.define "db1" do |db1|
        db1.vm.box = "bento/ubuntu-20.04-arm64"
        db1.vm.hostname = "db1"
    end
end