---
- name: Configure webserver with nginx
  hosts: dev
  become: true
  vars:
    homepage: /usr/share/nginx/html/index.html
  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        update_cache: true

    - name: Copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0755'

    - name: Enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Copy home page
      copy:
        src: "files/{{ homepage | basename }}"
        dest: "{{ homepage }}"
        mode: '0755'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
...
