---
- name: Test new role from within this playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: foo.bar.my_role
        tasks_from: main.yml
