Vagrant.configure(2) do |config|
    # disable guest addtions
    config.vm.synced_folder '.', '/vagrant', disable: true

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "bento/ubuntu-22.04-arm64"
    end

    config.vm.define "fedora" do |fedora|
        fedora.vm.box = "bento/fedora-39-arm64"
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = "bento/debian-12.4-arm64"
    end
end