---

- name: Nginx configuration
  become: true
  hosts:
    - dev
    - staging
    - prod

  tasks:
    - name: Nginx tasks
      include_tasks: nginx_include.yml
      when: ansible_os_family == 'RedHat'
      tags: nginx

    - name: Play platform specific actions
      include_tasks: "{{ ansible_os_family }}.yml"

- name: Configure staging server
  hosts: staging
  become: true
  tasks:

    - name: Install nginx
      yum:
        pkg: nginx
        state: latest

    - name: Install php
      include_role:
        name: php
        tasks_from: install

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0755'

    - name: Configure php
      include_role:
        name: php
        tasks_from: configure

- name: Show block demo
  hosts: dev,prerelease
  tasks:
    - name: Block demo
      become: true
      when: ansible_os_family == 'RedHat'
      block:
        - name: Install nginx
          package:
            name: nginx
            state: latest

        - name: Ensure nginx is running
          service:
            name: nginx
            state: started
            enabled: true
