---

- name: Chapter 10 examples
  hosts: localhost
  connection: local

  tasks:
    - name: Test of filter plugin
      template:
        src: example-10-10.j2
        dest: ./example.txt
        mode: '0644'

- name: Chapter 10 examples
  hosts:
    - dev
    - prod

  tasks:
    - name: Add my public key for SSH
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', item) }}"
      with_first_found:
        - ~/.ssh/id_ed25519.pub
        - ~/.ssh/id_rsa.pub
        - ~/.ssh/id_ecdsa.pub

    - name: Copy authorized_keys template
      template:
        src: authorized_keys.j2
        dest: /home/vagrant/.ssh/authorized_keys_demo
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Add default public key for vagrant user
      authorized_key:
        user: vagrant
        key: "{{ lookup('pipe', pubkey_cmd) }}"
      vars:
        pubkey_cmd: 'ssh-keygen -y -f ~/.vagrant.d/insecure_private_key'

    - name: Get the current shell
      debug:
        msg: "{{ lookup('env', 'SHELL') }}"

    - name: Create deploy user, save random password in pw.txt
      become: true
      user:
        name: deploy
        password: "{{ lookup('password', 'pw.txt encrypt=sha512_crypt') }}"

    - name: Output message from template
      debug:
        msg: "{{ lookup('template', 'message.j2') }}"

- name: More examples from chapter 10
  hosts: localhost
  connection: local

  tasks:
    - name: "Show Sue's email"
      debug:
        msg: "{{ lookup('csvfile', username + ' file=users.csv delimiter=, col=1') }}"
      vars:
        username: john

    - name: Look up TXT record
      debug:
        msg: "{{ lookup('dig', 'ansiblebook.com', 'qtype=TXT') }}"

    - name: Look up values in Redis
      debug:
        msg: "{{ lookup('redis', 'weather', 'temp') }}"

    - name: Unarchive maven
      vars:
        maven_url: "{{ ansible_env['HOME'] }}/apache-maven-3.9.6-bin.zip"
        maven_location: "{{ ansible_env['HOME'] }}/maven"
      unarchive:
        src: "{{ maven_url }}"
        dest: "{{ maven_location }}"
        remote_src: true
        mode: '0755'
      register: maven_download
      until: maven_download.failed == false
      retries: 5
      delay: 3
      ignore_errors: true

    - name: Display maven download result
      debug:
        var: maven_download

    - name: Iterate with lookup
      debug:
        msg: "KPI: {{ item.kpi }} prio: {{ i + 1 }} goto: {{ item.dept }}"
      loop:
        - kpi: availability
          dept: operations
        - kpi: performance
          dept: development
        - kpi: security
          dept: security
      loop_control:
        index_var: i
        pause: 3

    - name: Iterate over lines in a file
      debug:
        msg: "{{ item }}"
      with_lines:
        - cat files/turing.txt

- name: Chapter 10 loop examples
  hosts:
    - dev
    - prod
  tasks:
    - name: Install package
      become: true
      vars:
        list_of_packages:
          - git
          - wget
      package:
        name: "{{ list_of_packages }}"
        state: latest

    - name: Add public keys to account
      become: true
      authorized_key:
        user: deploy
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - ~/.ssh/id_rsa.pub
        - ~/.ssh/id_ed25519.pub

    - name: Iterate over ansible_eth0
      debug:
        msg: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ ansible_eth0.ipv4 }}"

    - name: Add users
      become: true
      user:
        name: "{{ user.name }}"
      with_items:
        - { name: gil }
        - { name: sarina }
        - { name: leanne }
      loop_control:
        loop_var: user

    - name: Install nginx
      become: true
      package:
        name: nginx
        update_cache: true

    - name: Run a set of tasks in one loop
      include_tasks: vhosts.yml
      with_items:
        - { domain: www1.example.com }
        - { domain: www2.example.com }
        - { domain: www3.example.com }
      loop_control:
        loop_var: vhost
