---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: ubuntu-jammy
    image: ubuntu:jammy
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    log_driver: json-file
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

  - name: oraclelinux-9
    image: oraclelinux:9
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    log_driver: json-file
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

  - name: alpine-3.19
    image: alpine:3.19
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
  log: true
