---

- name: Test group vars
  hosts: vagrant
  tasks:
    - name: Show vars in production
      debug:
        msg: "{{ myvar }}"

    - name: Concatenate variables
      debug:
        msg: "The URL is https://{{ server_name ~'.'~ domain_name }}" # concatenate variables with tilde
