---
- name: Prepare target environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    container_inventory:
      all:
        hosts: {}
        children:
          container: {}

  tasks:

    - name: Provision a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep 1d
      register: result
      with_items:
        - "{{ molecule_yml.platforms }}"

    - name: Display provision result
      ansible.builtin.debug:
        var: result
