---
- name: Install critical and security updates
  ansible.windows.win_updates:
    category_names:
      - CriticalUpdates
      - SecurityUpdates
    state: installed
  register: update_result

- name: Show update result
  ansible.builtin.debug:
    var: update_result

- name: Reboot if required
  ansible.windows.win_reboot:
  when: update_result.reboot_required
...
