Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-20.04-arm64"

    # Use the default insecure key for these machine
    config.ssh.insert_key = false

    config.vm.define 'web' do |web|
    end

end