Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-20.04-arm64"

    # Use the default insecure key for these machine
    config.ssh.insert_key = false

    # Use ssh-agent for cloning from Github.com
    config.ssh.forward_agent = true
    # disable guest additions
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define 'db' do |db|
    end

    config.vm.define 'web' do |web|
    end

end