---
- name: Configure webserver with nginx
  hosts: webservers
  become: true
  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        update_cache: true
      notify: Restart nginx

    - name: Copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart nginx

    - name: Enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart nginx

    - name: Install home page
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
      notify: Restart nginx

    - name: Restart nginx
      meta: flush_handlers

    - name: "Test it! http://{{ ansible_enp0s1.ipv4.address }}/index.html"
      delegate_to: localhost
      become: false
      uri:
        url: 'http://{{ ansible_enp0s1.ipv4.address }}/index.html'
        validate_certs: false
        return_content: true
      register: this
      failed_when: "'Running on' not in this.content"
      tags:
        - test

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
...
