---
- name: Ensure group developers
  ansible.windows.win_group:
    name: developers

- name: Ensure ansible user exists
  ansible.windows.win_user:
    name: ansible
    password: 'oarnud9I'
    groups: developers
    password_expired: true
    groups_action: add

- name: Manage tools directory
  ansible.windows.win_file:
    path: 'C:/Tools'
    state: directory

- name: Manage Features
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: absent
  loop: "{{ win_config_windows_features_remove }}"

- name: Manage IIS Web-Server with sub features and management tools
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_sub_features: true
    include_management_tools: true
  register: win_iis_feature

- name: Show win_iis_feature result
  ansible.builtin.debug:
    var: win_iis_feature

- name: Reboot if installing Web-Server feature requires it
  ansible.windows.win_reboot:
  when: win_iis_feature.reboot_required
...
